# Generated by Django 5.1.6 on 2025-05-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='days',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='days',
            field=models.ManyToManyField(to='base.day'),
        ),
    ]
